//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceCheckUp.Api.finansmanEntegrasyonWebService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.teminat.finansman.uut.cs.com.tr/", ConfigurationName="FinanceCheckUp.Api.finansmanEntegrasyonWebService.FinansmanEntegrasyonWebService")]
    public interface FinansmanEntegrasyonWebService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.teminat.finansman.uut.cs.com.tr/FinansmanEntegrasyonWebService/us" +
            "erValidationByQnbUserIdRequest", ReplyAction="http://services.teminat.finansman.uut.cs.com.tr/FinansmanEntegrasyonWebService/us" +
            "erValidationByQnbUserIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FinanceCheckUp.Api.finansmanEntegrasyonWebService.userValidationByQnbUserIdResponse> userValidationByQnbUserIdAsync(FinanceCheckUp.Api.finansmanEntegrasyonWebService.userValidationByQnbUserIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.teminat.finansman.uut.cs.com.tr/FinansmanEntegrasyonWebService/us" +
            "erValidationByUserIdPasswordRequest", ReplyAction="http://services.teminat.finansman.uut.cs.com.tr/FinansmanEntegrasyonWebService/us" +
            "erValidationByUserIdPasswordResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FinanceCheckUp.Api.finansmanEntegrasyonWebService.userValidationByUserIdPasswordResponse> userValidationByUserIdPasswordAsync(FinanceCheckUp.Api.finansmanEntegrasyonWebService.userValidationByUserIdPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.teminat.finansman.uut.cs.com.tr/FinansmanEntegrasyonWebService/de" +
            "fterIzinKaydetRequest", ReplyAction="http://services.teminat.finansman.uut.cs.com.tr/FinansmanEntegrasyonWebService/de" +
            "fterIzinKaydetResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FinanceCheckUp.Api.finansmanEntegrasyonWebService.defterIzinKaydetResponse> defterIzinKaydetAsync(FinanceCheckUp.Api.finansmanEntegrasyonWebService.defterIzinKaydetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.teminat.finansman.uut.cs.com.tr/FinansmanEntegrasyonWebService/de" +
            "fterIzinSilRequest", ReplyAction="http://services.teminat.finansman.uut.cs.com.tr/FinansmanEntegrasyonWebService/de" +
            "fterIzinSilResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FinanceCheckUp.Api.finansmanEntegrasyonWebService.defterIzinSilResponse> defterIzinSilAsync(FinanceCheckUp.Api.finansmanEntegrasyonWebService.defterIzinSilRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.teminat.finansman.uut.cs.com.tr/")]
    public partial class responseType
    {
        
        private string responseCodeField;
        
        private string responseMessageField;
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string responseCode
        {
            get
            {
                return this.responseCodeField;
            }
            set
            {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string responseMessage
        {
            get
            {
                return this.responseMessageField;
            }
            set
            {
                this.responseMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="userValidationByQnbUserId", WrapperNamespace="http://services.teminat.finansman.uut.cs.com.tr/", IsWrapped=true)]
    public partial class userValidationByQnbUserIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.teminat.finansman.uut.cs.com.tr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string vknTckn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.teminat.finansman.uut.cs.com.tr/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string qnbUserId;
        
        public userValidationByQnbUserIdRequest()
        {
        }
        
        public userValidationByQnbUserIdRequest(string vknTckn, string qnbUserId)
        {
            this.vknTckn = vknTckn;
            this.qnbUserId = qnbUserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="userValidationByQnbUserIdResponse", WrapperNamespace="http://services.teminat.finansman.uut.cs.com.tr/", IsWrapped=true)]
    public partial class userValidationByQnbUserIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.teminat.finansman.uut.cs.com.tr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FinanceCheckUp.Api.finansmanEntegrasyonWebService.responseType @return;
        
        public userValidationByQnbUserIdResponse()
        {
        }
        
        public userValidationByQnbUserIdResponse(FinanceCheckUp.Api.finansmanEntegrasyonWebService.responseType @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="userValidationByUserIdPassword", WrapperNamespace="http://services.teminat.finansman.uut.cs.com.tr/", IsWrapped=true)]
    public partial class userValidationByUserIdPasswordRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.teminat.finansman.uut.cs.com.tr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string vknTckn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.teminat.finansman.uut.cs.com.tr/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string kulaniciKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.teminat.finansman.uut.cs.com.tr/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sifre;
        
        public userValidationByUserIdPasswordRequest()
        {
        }
        
        public userValidationByUserIdPasswordRequest(string vknTckn, string kulaniciKodu, string sifre)
        {
            this.vknTckn = vknTckn;
            this.kulaniciKodu = kulaniciKodu;
            this.sifre = sifre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="userValidationByUserIdPasswordResponse", WrapperNamespace="http://services.teminat.finansman.uut.cs.com.tr/", IsWrapped=true)]
    public partial class userValidationByUserIdPasswordResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.teminat.finansman.uut.cs.com.tr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FinanceCheckUp.Api.finansmanEntegrasyonWebService.responseType @return;
        
        public userValidationByUserIdPasswordResponse()
        {
        }
        
        public userValidationByUserIdPasswordResponse(FinanceCheckUp.Api.finansmanEntegrasyonWebService.responseType @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="defterIzinKaydet", WrapperNamespace="http://services.teminat.finansman.uut.cs.com.tr/", IsWrapped=true)]
    public partial class defterIzinKaydetRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.teminat.finansman.uut.cs.com.tr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string vknTckn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.teminat.finansman.uut.cs.com.tr/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string hedefKaynak;
        
        public defterIzinKaydetRequest()
        {
        }
        
        public defterIzinKaydetRequest(string vknTckn, string hedefKaynak)
        {
            this.vknTckn = vknTckn;
            this.hedefKaynak = hedefKaynak;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="defterIzinKaydetResponse", WrapperNamespace="http://services.teminat.finansman.uut.cs.com.tr/", IsWrapped=true)]
    public partial class defterIzinKaydetResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.teminat.finansman.uut.cs.com.tr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FinanceCheckUp.Api.finansmanEntegrasyonWebService.responseType @return;
        
        public defterIzinKaydetResponse()
        {
        }
        
        public defterIzinKaydetResponse(FinanceCheckUp.Api.finansmanEntegrasyonWebService.responseType @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="defterIzinSil", WrapperNamespace="http://services.teminat.finansman.uut.cs.com.tr/", IsWrapped=true)]
    public partial class defterIzinSilRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.teminat.finansman.uut.cs.com.tr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string vknTckn;
        
        public defterIzinSilRequest()
        {
        }
        
        public defterIzinSilRequest(string vknTckn)
        {
            this.vknTckn = vknTckn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="defterIzinSilResponse", WrapperNamespace="http://services.teminat.finansman.uut.cs.com.tr/", IsWrapped=true)]
    public partial class defterIzinSilResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.teminat.finansman.uut.cs.com.tr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FinanceCheckUp.Api.finansmanEntegrasyonWebService.responseType @return;
        
        public defterIzinSilResponse()
        {
        }
        
        public defterIzinSilResponse(FinanceCheckUp.Api.finansmanEntegrasyonWebService.responseType @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface FinansmanEntegrasyonWebServiceChannel : FinanceCheckUp.Api.finansmanEntegrasyonWebService.FinansmanEntegrasyonWebService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class FinansmanEntegrasyonWebServiceClient : System.ServiceModel.ClientBase<FinanceCheckUp.Api.finansmanEntegrasyonWebService.FinansmanEntegrasyonWebService>, FinanceCheckUp.Api.finansmanEntegrasyonWebService.FinansmanEntegrasyonWebService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FinansmanEntegrasyonWebServiceClient() : 
                base(FinansmanEntegrasyonWebServiceClient.GetDefaultBinding(), FinansmanEntegrasyonWebServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.FinansmanEntegrasyonWebServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FinansmanEntegrasyonWebServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(FinansmanEntegrasyonWebServiceClient.GetBindingForEndpoint(endpointConfiguration), FinansmanEntegrasyonWebServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FinansmanEntegrasyonWebServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FinansmanEntegrasyonWebServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FinansmanEntegrasyonWebServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FinansmanEntegrasyonWebServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FinansmanEntegrasyonWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FinanceCheckUp.Api.finansmanEntegrasyonWebService.userValidationByQnbUserIdResponse> FinanceCheckUp.Api.finansmanEntegrasyonWebService.FinansmanEntegrasyonWebService.userValidationByQnbUserIdAsync(FinanceCheckUp.Api.finansmanEntegrasyonWebService.userValidationByQnbUserIdRequest request)
        {
            return base.Channel.userValidationByQnbUserIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<FinanceCheckUp.Api.finansmanEntegrasyonWebService.userValidationByQnbUserIdResponse> userValidationByQnbUserIdAsync(string vknTckn, string qnbUserId)
        {
            FinanceCheckUp.Api.finansmanEntegrasyonWebService.userValidationByQnbUserIdRequest inValue = new FinanceCheckUp.Api.finansmanEntegrasyonWebService.userValidationByQnbUserIdRequest();
            inValue.vknTckn = vknTckn;
            inValue.qnbUserId = qnbUserId;
            return ((FinanceCheckUp.Api.finansmanEntegrasyonWebService.FinansmanEntegrasyonWebService)(this)).userValidationByQnbUserIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FinanceCheckUp.Api.finansmanEntegrasyonWebService.userValidationByUserIdPasswordResponse> FinanceCheckUp.Api.finansmanEntegrasyonWebService.FinansmanEntegrasyonWebService.userValidationByUserIdPasswordAsync(FinanceCheckUp.Api.finansmanEntegrasyonWebService.userValidationByUserIdPasswordRequest request)
        {
            return base.Channel.userValidationByUserIdPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<FinanceCheckUp.Api.finansmanEntegrasyonWebService.userValidationByUserIdPasswordResponse> userValidationByUserIdPasswordAsync(string vknTckn, string kulaniciKodu, string sifre)
        {
            FinanceCheckUp.Api.finansmanEntegrasyonWebService.userValidationByUserIdPasswordRequest inValue = new FinanceCheckUp.Api.finansmanEntegrasyonWebService.userValidationByUserIdPasswordRequest();
            inValue.vknTckn = vknTckn;
            inValue.kulaniciKodu = kulaniciKodu;
            inValue.sifre = sifre;
            return ((FinanceCheckUp.Api.finansmanEntegrasyonWebService.FinansmanEntegrasyonWebService)(this)).userValidationByUserIdPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FinanceCheckUp.Api.finansmanEntegrasyonWebService.defterIzinKaydetResponse> FinanceCheckUp.Api.finansmanEntegrasyonWebService.FinansmanEntegrasyonWebService.defterIzinKaydetAsync(FinanceCheckUp.Api.finansmanEntegrasyonWebService.defterIzinKaydetRequest request)
        {
            return base.Channel.defterIzinKaydetAsync(request);
        }
        
        public System.Threading.Tasks.Task<FinanceCheckUp.Api.finansmanEntegrasyonWebService.defterIzinKaydetResponse> defterIzinKaydetAsync(string vknTckn, string hedefKaynak)
        {
            FinanceCheckUp.Api.finansmanEntegrasyonWebService.defterIzinKaydetRequest inValue = new FinanceCheckUp.Api.finansmanEntegrasyonWebService.defterIzinKaydetRequest();
            inValue.vknTckn = vknTckn;
            inValue.hedefKaynak = hedefKaynak;
            return ((FinanceCheckUp.Api.finansmanEntegrasyonWebService.FinansmanEntegrasyonWebService)(this)).defterIzinKaydetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FinanceCheckUp.Api.finansmanEntegrasyonWebService.defterIzinSilResponse> FinanceCheckUp.Api.finansmanEntegrasyonWebService.FinansmanEntegrasyonWebService.defterIzinSilAsync(FinanceCheckUp.Api.finansmanEntegrasyonWebService.defterIzinSilRequest request)
        {
            return base.Channel.defterIzinSilAsync(request);
        }
        
        public System.Threading.Tasks.Task<FinanceCheckUp.Api.finansmanEntegrasyonWebService.defterIzinSilResponse> defterIzinSilAsync(string vknTckn)
        {
            FinanceCheckUp.Api.finansmanEntegrasyonWebService.defterIzinSilRequest inValue = new FinanceCheckUp.Api.finansmanEntegrasyonWebService.defterIzinSilRequest();
            inValue.vknTckn = vknTckn;
            return ((FinanceCheckUp.Api.finansmanEntegrasyonWebService.FinansmanEntegrasyonWebService)(this)).defterIzinSilAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FinansmanEntegrasyonWebServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FinansmanEntegrasyonWebServicePort))
            {
                return new System.ServiceModel.EndpointAddress("https://connector.efinans.com.tr/connector/ws/finansmanEntegrasyonWebService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return FinansmanEntegrasyonWebServiceClient.GetBindingForEndpoint(EndpointConfiguration.FinansmanEntegrasyonWebServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return FinansmanEntegrasyonWebServiceClient.GetEndpointAddress(EndpointConfiguration.FinansmanEntegrasyonWebServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            FinansmanEntegrasyonWebServicePort,
        }
    }
}
